FROM ubuntu:20.04
RUN apt-get update -y
RUN apt-get install -y curl python-dev build-essential
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python get-pip.py
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
CMD ["environment/app.py"]
