version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "**/*"
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "pip"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    groups:
      grpcio:
        patterns:
          - "grpcio*"
        update-types:
          - "minor"
          - "patch"
