change:
  - head-branch: ['^change/']

enhancement:
  - head-branch: ['^feature/', '^feat/', '^enhancement/', '^enh/']

bug:
  - head-branch: ['^fix/', '^bug/']

chore:
  - head-branch: ['^chore/']

documentation:
  - head-branch: ['^docs/', '^doc/']
  - changed-files: '**/*.md'

dependencies:
  - head-branch: ['^deps/', '^dep/', '^dependabot/', 'pre-commit-ci-update-config']

tests:
  - any:
      - head-branch: ['^tests/', '^test/']
      - changed-files: ['test/**/*']
  - all:
      - changed-files: ['!test/requirements.txt']
