change:
  - head-branch: ['^change/']

enhancement:
  - head-branch: ['^feature/', '^feat/', '^enhancement/', '^enh/']

bug:
  - head-branch: ['^fix/', '^bug/']

chore:
  - head-branch: ['^chore/']

documentation:
  - head-branch: ['^docs/', '^doc/']
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

dependencies:
  - head-branch: ['^deps/', '^dep/', '^dependabot/', 'pre-commit-ci-update-config']

tests:
  - any:
      - head-branch: ['^tests/', '^test/']
      - changed-files:
        - any-glob-to-any-file: 'test/**/*'
  - all:
      - changed-files:
        - all-globs-to-all-files: '!test/requirements.txt'
