name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - "enhancement"
  - title: '💣 Breaking Change'
    labels:
      - "change"
  - title: '🐛 Bug Fixes'
    labels:
      - "bug"
  - title: '📝 Documentation'
    labels:
      - "documentation"
  - title: '🔨 Maintenance'
    labels:
      - "chore"
  - title: '⬆️ Dependencies'
    labels:
      - "dependencies"
version-resolver:
  major:
    labels:
      - 'change'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'documentation'
  default: patch
exclude-labels:
  - 'skip-changelog'
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/enh\/.+/'
      - '/enhancement\/.+/'
      - '/feat\/.+/'
      - '/feature\/.+/'
    title:
      - '/feat/i'
  - label: 'dependencies'
    branch:
      - '/deps\/.+/'
template: |
  ## New in NGINX plugin for OpenTracing v$RESOLVED_VERSION

  $CHANGES
