FROM ubuntu:18.04

ARG OPENTRACING_CPP_VERSION=v1.4.0
ARG NGINX_VERSION=1.13.12

COPY . /src

RUN set -x \
  && apt-get update \
  && apt-get install --no-install-recommends --no-install-suggests -y \
              build-essential \
              gettext \
              cmake \
              git \
              gnupg2 \
              software-properties-common \
              curl \
              python3 \
              jq \
              ca-certificates \
              wget \
              libpcre3 libpcre3-dev \
              zlib1g-dev \
### Install clang (gcc has this problem when using with address sanitizer:
### https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84428)
  && wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
  && apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" \
  && apt-get update \
  && apt-get install -y clang-6.0 \
  && export CC=/usr/bin/clang-6.0 \
  && export CXX=/usr/bin/clang++-6.0 \
### Build opentracing-cpp
  && cd / \
  && git clone -b $OPENTRACING_CPP_VERSION https://github.com/opentracing/opentracing-cpp.git \
  && cd opentracing-cpp \
  && mkdir .build && cd .build \
  && cmake -DCMAKE_BUILD_TYPE=Debug \
           -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=address" \
           -DCMAKE_SHARED_LINKER_FLAGS="-fno-omit-frame-pointer -fsanitize=address" \
           -DCMAKE_EXE_LINKER_FLAGS="-fno-omit-frame-pointer -fsanitize=address" \
           -DBUILD_TESTING=OFF .. \
  && make && make install \
### Build nginx
  && cd /src \
  && wget -O nginx-release-${NGINX_VERSION}.tar.gz https://github.com/nginx/nginx/archive/release-${NGINX_VERSION}.tar.gz \
  && tar zxf nginx-release-${NGINX_VERSION}.tar.gz \
  && cd /src/nginx-release-${NGINX_VERSION} \
  # Temporarily disable leak sanitizer to get around false positives in build
  && export ASAN_OPTIONS=detect_leaks=0 \
  && auto/configure \
      --with-compat \
      --with-debug \
      --with-cc-opt="-O1 -g -fno-omit-frame-pointer -fsanitize=address" \
      --with-ld-opt="-g -fno-omit-frame-pointer -fsanitize=address" \
      --add-dynamic-module=/src/opentracing \
  && make && make install
CMD ["/usr/local/nginx/sbin/nginx", "-g", "daemon off;"]
