version: '2'
services:

  nginx:
    image: opentracing/nginx-opentracing
    networks:
      php_example:
        aliases:
          - nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./jaeger-config.json:/etc/jaeger-config.json
    expose:
      - "8080"
    ports:
      - "8080:8080"

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      php_example:
        aliases:
          - jaeger
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"

  php_fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      php_example:
        aliases:
          - php_fpm
    volumes:
      - ./app.php:/var/www/app.php
    expose:
      - "9000"
    ports:
      - "9000:9000"

networks:
  php_example: {}
