# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app_pb2 as app__pb2


class AppStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CheckTraceHeader = channel.unary_unary(
        '/App/CheckTraceHeader',
        request_serializer=app__pb2.Empty.SerializeToString,
        response_deserializer=app__pb2.Empty.FromString,
        )


class AppServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CheckTraceHeader(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AppServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CheckTraceHeader': grpc.unary_unary_rpc_method_handler(
          servicer.CheckTraceHeader,
          request_deserializer=app__pb2.Empty.FromString,
          response_serializer=app__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'App', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
