name: Docker

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master

env:
  PLATFORMS: "linux/arm,linux/amd64,linux/arm64,linux/ppc64le,linux/s390x"

jobs:
    build-docker:
      name: Build Docker Image
      runs-on: ubuntu-20.04
      strategy:
        matrix:
          os: [debian, alpine]
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Output Variables
          id: var
          run: |
            echo "::set-output name=nginx_version::$(grep -m1 'FROM nginx:' <Dockerfile | awk -F'[: ]' '{print $3}')"

        - name: Setup QEMU
          uses: docker/setup-qemu-action@v1
          with:
            platforms: arm,arm64,ppc64le,s390x
          if: github.event_name != 'pull_request'

        - name: Docker Buildx
          uses: docker/setup-buildx-action@v1
          with:
            buildkitd-flags: --debug

        - name: DockerHub Login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          if: github.event_name != 'pull_request'

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
          if: github.event_name != 'pull_request'

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v3
          with:
            images: |
              opentracing/nginx-opentracing
              ghcr.io/opentracing-contrib/nginx-opentracing
            flavor: suffix=${{ matrix.os != 'debian' && '-' || '' }}${{ matrix.os != 'debian' && matrix.os || '' }},onlatest=true
            tags: |
              type=edge
              type=ref,event=pr
              type=semver,pattern={{version}}
              type=raw,value=nginx-${{ steps.var.outputs.nginx_version }},enable=${{ contains(github.ref, 'refs/tags/') }}

        - name: Build (and push if not PR)
          uses: docker/build-push-action@v2
          with:
            pull: true
            load: ${{ github.event_name == 'pull_request' }}
            push: ${{ github.event_name != 'pull_request' }}
            platforms: ${{ github.event_name != 'pull_request' && env.PLATFORMS || '' }}
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
            cache-from: type=gha,scope=${{ matrix.os }}
            cache-to: type=gha,scope=${{ matrix.os }},mode=max
            target: final
            build-args: BUILD_OS=${{ matrix.os }}
