name: Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref_name }}-lint
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Mise
        uses: jdx/mise-action@v4

      - name: Install dependencies
        run: |
          mise deps

      - name: Run lint
        run: |
          mise run lint --no-progress

  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -shellcheck ""

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          config: .markdownlint-cli2.yaml
          globs: '**/*.md'
          fix: false
